spring:
  thymeleaf:
    prefix: classpath:/app/dist/

freelancers-hub:
  token-audience: www.freelancers-hub.org
  token-issuer: www.freelancers-hub.org
  users:
    - authorities: ADMIN
      password: andrey
      username: andrey
      accountExpiredAt: 2024-05-24T00:00:00Z
      accountLocked: false
      credentialsExpiredAt: 2024-05-24T00:00:00Z
      enabled: true

logging:
  config: logging-config.xml # classpath:logging-config.xml - logback
