freelancers-hub:
  token-audience: www.freelancers-hub.org
  token-issuer: www.freelancers-hub.org
  users:
    - authorities: ADMIN
      password: andrey
      username: andrey
      enabled: true

logging:
  config: classpath:logging-config.xml # logging-config.xml - logback
