freelancers-hub:
  mail:
    smtp:
      host: # specify
      port: # specify
      username: # specify
      password: # specify
  security:
    accessToken:
      expirationMs: 45000
    refreshToken:
      expirationMs: 90000
    passwordResetToken:
      expirationMs: 180000

  users:
    - email: # specify
      authorities: ADMIN
      password: andrey
      username: andrey
      enabled: true

logging:
  config: classpath:logging-config.xml # logging-config.xml - logback
